import "@/styles/globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [ {
		rel: "icon",
		url: "/favicon.ico",
	} ],
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	const locale = await getLocale();
 
	// Providing all messages to the client
	// side is the easiest way to get started
	const messages = await getMessages();
 
	return (
		<html
			lang={locale}
			dir={locale === "he" ? "rtl" : "ltr"}
			className={`${GeistSans.variable}`}
		>
			<body>
				<NextIntlClientProvider messages={messages}>
					<TRPCReactProvider>{children}</TRPCReactProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
