import { type User, UserRole } from "@prisma/client";
import { addDays, addMonths } from "date-fns";
import { seedOrganizations } from "prisma/seed-data/seed-organizations";

export const seedUsers = [
	{
		id: "user1",
		firstName: "alon",
		lastName: "aiden",
		email: "user1@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -2),
		retireDate: addMonths(new Date(), 2),
		role: UserRole.SQUAD,
	},
	{
		id: "user2",
		firstName: "bob",
		lastName: "biden",
		email: "user2@example.com",
		emailVerified: addMonths(new Date(), -3),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -5),
		retireDate: addMonths(new Date(), 10),
		role: UserRole.SQUAD,
	},
	{
		id: "user3",
		firstName: "cole",
		lastName: "cake",
		email: "user3@example.com",
		emailVerified: addMonths(new Date(), -2),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -5),
		retireDate: addMonths(new Date(), 20),
		role: UserRole.SQUAD,
	},
	{
		id: "user4",
		firstName: "dove",
		lastName: "dali",
		email: "user4@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -5),
		retireDate: addMonths(new Date(), 20),
		role: UserRole.SQUAD,
	},
	{
		id: "user5",
		firstName: "eric",
		lastName: "epsilon",
		email: "user5@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -2),
		retireDate: addMonths(new Date(), 2),
		role: UserRole.OFFICER,
	},
	{
		id: "user6",
		firstName: "fred",
		lastName: "funk",
		email: "user6@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -2),
		retireDate: addDays(new Date(), 45),
		role: UserRole.OFFICER,
	},
	{
		id: "user7",
		firstName: "gidi",
		lastName: "garlic",
		email: "user7@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -3),
		retireDate: addMonths(new Date(), 8),
		role: UserRole.COMMANDER,
	},
	{
		id: "user8",
		firstName: "haji",
		lastName: "hadad",
		email: "user8@example.com",
		emailVerified: addMonths(new Date(), -1),
		organizationId: seedOrganizations[0].id,
		isAdmin: false,
		roleStartDate: addMonths(new Date(), -2),
		retireDate: addMonths(new Date(), 10),
		role: UserRole.COMMANDER,
	},
] as const satisfies User[];
