-- CreateEnum
CREATE TYPE "DutyRoleRequirement" AS ENUM ('SQUAD', 'OFFICER', 'COMMANDER', 'EXEMPT', 'SQUAD_AND_EXEMPT', 'EXEMPT_AND_SQUAD', 'OFFICER_AND_COMMANDER', 'COMMANDER_AND_OFFICER', 'ANY');

-- AlterTable
ALTER TABLE "Duty" ADD COLUMN     "roleRequirement" "DutyRoleRequirement" NOT NULL DEFAULT 'ANY',
ALTER COLUMN "role" DROP NOT NULL;
